version: '3.5'
services:
    airflow-scheduler:
        image: apache/airflow:2.5.0
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - airflow
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/opt/airflow/plugins
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: rabbitmq
            CELERY_BROKER_USER: airflow
            CELERY_BROKER_PASSWORD: yey123456
            CELERY_BROKER_HOST: rabbitmq
            CELERY_BROKER_PORT: 5672
            INITDB: "True"
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow scheduler
    airflow-webserver:
        image: apache/airflow:2.5.0
        depends_on:
            - mysql
            - rabbitmq
        ports:
            - 8180:8080
        networks:
            - airflow
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/opt/airflow/plugins
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: rabbitmq
            CELERY_BROKER_USER: airflow
            CELERY_BROKER_PASSWORD: yey123456
            CELERY_BROKER_HOST: rabbitmq
            CELERY_BROKER_PORT: 5672
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow webserver
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "[ -f /opt/airflow/airflow-webserver.pid ]"
                ]
            interval: 30s
            timeout: 30s
            retries: 3
    airflow-worker:
        image: apache/airflow:2.5.0
        depends_on:
            - mysql
            - rabbitmq
        networks:
            - airflow
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./plugins:/opt/airflow/plugins
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: rabbitmq
            CELERY_BROKER_USER: airflow
            CELERY_BROKER_PASSWORD: yey123456
            CELERY_BROKER_HOST: rabbitmq
            CELERY_BROKER_PORT: 5672
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow worker
    airflow-flower:
        image: apache/airflow:2.5.0
        depends_on:
            - mysql
            - rabbitmq
        ports:
            - 5555:5555
        networks:
            - airflow
        environment:
            EXECUTOR: CeleryExecutor
            BACKEND: mysql
            BACKEND_USER: airflow
            BACKEND_PASSWORD: yey123456
            BACKEND_DATABASE: airflow
            BACKEND_HOST: mysql
            BACKEND_PORT: 3306
            BROKER: rabbitmq
            CELERY_BROKER_USER: airflow
            CELERY_BROKER_PASSWORD: yey123456
            CELERY_BROKER_HOST: rabbitmq
            CELERY_BROKER_PORT: 5672
            FERNET_KEY: NXtEyKwp633TUtAgdyoEonj9ufHRI7I33s3wjw3q0yU=
        command: airflow flower
    mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        networks:
            - airflow
        volumes:
            - mysql-db-volume:/var/lib/mysql
        environment:
            MYSQL_USER: airflow
            MYSQL_PASSWORD: yey123456
            MYSQL_DATABASE: airflow
            MYSQL_ROOT_PASSWORD: iamroot321654
    rabbitmq:
        image: rabbitmq:3.7.3
        networks:
            - airflow
        environment:
            RABBITMQ_DEFAULT_USER: airflow
            RABBITMQ_DEFAULT_PASS: yey123456
            RABBITMQ_DEFAULT_VHOST: airflow
networks:
    airflow:
volumes:
    mysql-db-volume:
